project:
  type: book
  resources:
  - "data/*"

book:
  title: "Zbiór zadań - Analiza i Wizualizacja Danych"
  author: Piotr Jastrzębski
  date: today
  cover-image: logo-aiwd.jpg
  chapters:
    - index.qmd
    - references.qmd
  downloads: pdf
  repo-url: https://github.com/pjastr/zbior-zadan-aiwd
  repo-actions: [issue]


bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: pl
  pdf:
    lang: pl
    header-includes: |
      \titlehead{\includegraphics[width=6in]{logo-aiwd.jpg}}


editor: visual

